services:
  cppdev:
    build:
      context: .
      dockerfile: Dockerfile
    image: atcode
    container_name: atcode
    volumes:
      - type: bind
        source: .
        target: /atcode
    stdin_open: true
    tty: true
    working_dir: /atcode/src
